# Generated by Django 6.0.5 on 2026-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_status'),
        ('doctor', '0001_initial'),
        ('patient', '0002_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'time'), name='unique_appointment'),
        ),
    ]
