# Generated by Django 6.0.5 on 2026-06-05 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter valid Indian phone number (10 digits starting from 6-9)', regex='^[6-9]\\d{9}$')]),
        ),
    ]
