# Generated by Django 6.0.7 on 2026-08-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Monday-Friday', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(default='09:00 AM - 05:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Experience in years'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(default='MBBS', max_length=150),
        ),
    ]
